name = "MusicManipulations"
uuid = "274955c0-c284-5bf7-b122-5ecd51c559de"
repo = "https://github.com/JuliaMusic/MusicManipulations.jl.git"
version = "0.8.3"

[deps]
DefaultApplication = "3f0dd361-4fe0-5fc6-8523-80b14ec94d85"
MIDI = "f57c4921-e30c-5f49-b073-3f2f2ada663e"
MotifSequenceGenerator = "7d228ccb-0fc9-53c8-a429-8c9b5b572bc3"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
MIDI = "1.4.1"
MotifSequenceGenerator = "â‰¥ 0.2.0"
julia = "1.1"
